# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Log in to Docker Hub
  inputs:
    command: login
    server: https://index.docker.io/v1/
    username: $(luansisbr89)
    password: $(Cloud@36226947)

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(luansisbr89/unyleya_pos)
    tags: $(imageTag)
    dockerfile: Dockerfile
    containerRegistry: 'DockerHubConnection'