# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Log in to Docker Hub
  inputs:
    command: login
    server: https://index.docker.io/v1/
    username: $(luansisbr89)
    password: $(Cloud@36226947)

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(luansisbr89/unyleya_pos)
    tags: $(imageTag)
    dockerfile: Dockerfile
    containerRegistry: https://index.docker.io/v1/