# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main  # Gatilho para o branch principal (ou outro branch)

pool:
  vmImage: 'ubuntu-latest'  # Máquina virtual usada no pipeline

steps:
# Etapa 1: Baixar código do GitHub
- task: UsePythonVersion@1
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: Checkout@1  # Clonar o código do repositório
  displayName: 'Checkout do Repositório'

# Etapa 2: Configurar Docker Build
- task: Docker@2
  displayName: 'Build da Imagem Docker'
  inputs:
    containerRegistry: 'docker'  # Nome da conexão no Azure
    repository: 'luansisbr89/unyleya_pos'                # Nome do repositório Docker
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

# Etapa 3: Executar Testes (Opcional)
- script: |
    python -m unittest
  displayName: 'Executar Testes Automatizados'