# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'luansisbr89/unyleya_pos'

steps:
# Passo 1: Baixar o arquivo seguro com as credenciais do Docker Hub
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'DOCKER_HUB_USERNAME=luansisbr89'
    name: 'dockerhubCredentials'
    retryCount: '3'

# Passo 2: Fazer login no Docker Hub
- script: |
    source $(dockerhubCredentials.secureFilePath)
    echo "Logging in to Docker Hub..."
    echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
  displayName: 'Login to Docker Hub'

# Passo 3: Construir e enviar a imagem Docker
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)